# -*- coding: utf-8 -*-
CLIPS = [
    {"id": "intro", "text": "Bienvenidos al campus NOV. La plataforma gestiona la capacitacion obligatoria del personal, con acceso separado para participantes y capacitadores."},
    {"id": "portal.participants", "text": "Participantes: el personal entra con su DNI habilitado y cursa lo asignado a su sector, puesto y tarea."},
    {"id": "portal.trainers", "text": "Capacitadores: publican salas, cursos, la matriz de competencias y controlan la vigencia."},
    {"id": "portal.progress", "text": "Progreso: el tablero ejecutivo de cumplimiento. Entramos por aca."},
    {"id": "admin.login", "text": "El capacitador ingresa con email y contrasena."},
    {"id": "progreso.kpis", "text": "El tablero muestra el cumplimiento por sede: vigente, por vencer, pendiente y vencida."},
    {"id": "progreso.filtros", "text": "Se filtra por alumno, DNI, sede, puesto, estado o curso, y se exporta el reporte en CSV."},
    {"id": "admin.panel", "text": "Este es el panel de capacitadores. Arriba esta el menu de gestion."},
    {"id": "admin.stats", "text": "El resumen muestra capacitaciones, personal con perfil, DNIs habilitados y salas activas."},
    {"id": "admin.rooms.home", "text": "Abajo, las salas tematicas agrupan los cursos por area."},
    {"id": "salas.intro", "text": "En Salas se crean las areas tematicas. Cada sala agrupa capacitaciones."},
    {"id": "salas.form", "text": "Para crear una: el nombre visible y, si hace falta, un identificador. Si el slug queda vacio, se genera solo."},
    {"id": "salas.list", "text": "Las salas existentes aparecen aca, con la cantidad de cursos de cada una."},
    {"id": "cursos.list", "text": "Aca estan los cursos publicados, organizados por sala. El boton rojo abre el alta."},
    {"id": "cursos.nueva", "text": "Formulario de alta: titulo, descripcion e imagen opcional para el alumno y el certificado."},
    {"id": "cursos.reglas", "text": "Se elige la sala, el puntaje minimo de aprobacion y los dias de vigencia del certificado."},
    {"id": "cursos.alcance", "text": "El alcance es obligatorio: sector, puesto y tarea. El curso solo llega a esa celda."},
    {"id": "cursos.publicar", "text": "Publicar hace visible el curso para los alumnos asignados. Sin el tilde, queda en borrador."},
    {"id": "cursos.material", "text": "Aca se sube el material: video, PDF o documentos de Office."},
    {"id": "cursos.quiz", "text": "La evaluacion es opcion multiple. Se marcan las respuestas correctas y se pueden agregar preguntas."},
    {"id": "cursos.guardar", "text": "Cuando esta listo, Crear capacitacion lo publica."},
    {"id": "matriz.intro", "text": "La matriz no es una inscripcion libre. Cada tema vive en una celda: puesto, tarea y sede."},
    {"id": "matriz.form", "text": "Para asignar un tema se elige la capacitacion y la interseccion. El cambio llega a los alumnos de esa celda."},
    {"id": "matriz.celdas", "text": "Abajo esta el mapa de celdas publicadas, con los temas de cada una."},
    {"id": "alumnos.alta", "text": "Nadie entra al campus sin un DNI habilitado. Se carga uno, o se importa un listado CSV."},
    {"id": "alumnos.csv", "text": "Importar CSV habilita documentos en lote. Exportar progreso baja el seguimiento en planilla."},
    {"id": "alertas.intro", "text": "Las alertas las ve todo el personal en el campus."},
    {"id": "alertas.form", "text": "Nueva alerta: titulo, mensaje, tipo informativa, advertencia o peligro, y una fecha de vencimiento opcional."},
    {"id": "campus.salida", "text": "Ahora el lado del participante. Salimos del panel y entramos con DNI."},
    {"id": "campus.login", "text": "El ingreso es solo con el documento."},
    {"id": "campus.terna", "text": "El campus saluda por nombre y muestra sector, puesto y tarea. De ahi salen las asignaciones."},
    {"id": "campus.tablero", "text": "El tablero separa vencidas, por vencer, asignadas y vigentes. El alumno cursa lo de su celda."},
    {"id": "campus.asignadas", "text": "En Asignadas estan los cursos obligatorios todavia dentro de vigencia. Cada tarjeta abre el material y la evaluacion."},
    {"id": "campus.vigentes", "text": "En Vigentes estan los cursos ya aprobados, con certificado valido."},
    {"id": "campus.cert", "text": "Al aprobar, el certificado se descarga en PDF, con puntaje y vigencia."},
    {"id": "campus.historial", "text": "El historial junta todos los certificados emitidos."},
    {"id": "cierre", "text": "El capacitador publica y controla; el personal cursa lo asignado y se certifica."},
]
